### ISSUE TITLE
Integrate `prettier`

### ISSUE THREAD

**Issue by ddanilovich-demo** [ddanilovich-demo/ng-demo#4]
### Tasks

- [x] Add `prettier` commands to the project.
- [x] Add a code format check before a commit using git hooks.
- [x] Format all the code with `prettier`

### Details

Install `prettier`

```shell
npm install --save-dev prettier pretty-quick
```

Add a `.prettierrc` config file

```json
{
  "$schema": "http://json.schemastore.org/prettierrc",
  "printWidth": 100,
  "singleQuote": true,
  "trailingComma": "all"
}
```

Add npm scripts

```json
{
  "prettier:run": "prettier --write \"**/*.{html,ts,tsx,js,jsx,cjs,mjs,vue,css,scss,less,json,md,mdx,yaml}\"",
  "prettier:check": "prettier --check \"**/*.{html,ts,tsx,js,jsx,cjs,mjs,vue,css,scss,less,json,md,mdx,yaml}\"",
  "pretty-quick:staged": "pretty-quick --staged"
}
```

Add a git commit hook

```shell
npx husky add .husky/pre-commit 'npm run pretty-quick:staged'
```

### References

- [prettier docs](https://prettier.io/docs/en/index.html)
