### ISSUE TITLE
Integrate `eslint`

### ISSUE THREAD

**Issue by ddanilovich-demo** [ddanilovich-demo/ng-demo#5]
### Tasks

- [ ] Add `eslint` command to the project.
- [ ] Add a code style check before a commit using git hooks.
- [ ] Fix all the `eslint` issues.

### Details

Install `eslint`

```shell
npm install --save-dev eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin
```

Add a `.eslintrc.js` config file:

```javascript
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  ignorePatterns: ['*.js', '*.html', '*.scss'],
  parserOptions: {
    tsconfigRootDir: __dirname,
    project: 'tsconfig.json',
    sourceType: 'module',
  },
  plugins: ['@typescript-eslint'],
  extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],
};
```

Add npm scripts

```json
{
  "eslint:check": "eslint ."
}
```

Add a git commit hook

```shell
npx husky add .husky/pre-commit 'npm run eslint:check'
```

## References

- [eslint docs](https://eslint.org/docs/user-guide/configuring/)
